"""
Django settings for wellbeing_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import json
from google.oauth2 import service_account

# ---------------------------------------------------------
# BASE DIRECTORY
# ---------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------
# SECRET KEY & DEBUG
# ---------------------------------------------------------
SECRET_KEY = 'django-insecure-6zg6dkd-&)*nr6k^65usiw=)o3buh-1ja1sp)!_eu!66*8^60h'
DEBUG = True

ALLOWED_HOSTS = [
    'wellbeing-dashboard-1.onrender.com',
    'localhost',
    '127.0.0.1'
]


# ---------------------------------------------------------
# APPLICATIONS
# ---------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'import_export',
]


# ---------------------------------------------------------
# MIDDLEWARE
# ---------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# ---------------------------------------------------------
# URLS & TEMPLATES
# ---------------------------------------------------------
ROOT_URLCONF = 'wellbeing_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wellbeing_project.wsgi.application'


# ---------------------------------------------------------
# DATABASE
# ---------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ---------------------------------------------------------
# LANGUAGE / TIMEZONE
# ---------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------
# URL for static files
STATIC_URL = '/static/'

# Where collectstatic will gather all static files (admin + custom)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optional folder for custom static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # make sure this folder exists
]

# WhiteNoise storage
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ---------------------------------------------------------
# DEFAULT FIELD TYPE
# ---------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------
# GOOGLE SHEETS AUTH CONFIG (LOCAL + RENDER)
# ---------------------------------------------------------
GOOGLE_SHEETS_SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]


def get_google_credentials():
    """
    Loads Google service account credentials.
    Works BOTH locally and on Render using environment variable.
    """

    # Render (environment variable)
    if os.environ.get("GOOGLE_CREDENTIALS_JSON"):
        creds_json = json.loads(os.environ["GOOGLE_CREDENTIALS_JSON"])
        return service_account.Credentials.from_service_account_info(
            creds_json, scopes=GOOGLE_SHEETS_SCOPES
        )

    # Local development (JSON file)
    service_file = os.path.join(BASE_DIR, "service_account.json")
    return service_account.Credentials.from_service_account_file(
        service_file, scopes=GOOGLE_SHEETS_SCOPES
    )
